const TUI_CODE_FILETYPE_BY_EXTENSION: Record<string, string> = {
  bash: 'bash',
  c: 'c',
  cc: 'cpp',
  cjs: 'javascript',
  cpp: 'cpp',
  cs: 'csharp',
  cts: 'typescript',
  ctsx: 'typescriptreact',
  cxx: 'cpp',
  css: 'css',
  dart: 'dart',
  eex: 'embedded_template',
  ejs: 'embedded_template',
  el: 'elisp',
  erb: 'embedded_template',
  ex: 'elixir',
  exs: 'elixir',
  go: 'go',
  h: 'c',
  'h++': 'cpp',
  hh: 'cpp',
  hpp: 'cpp',
  htm: 'html',
  html: 'html',
  hxx: 'cpp',
  java: 'java',
  js: 'javascript',
  json: 'json',
  jsonc: 'json',
  jsx: 'javascriptreact',
  ksh: 'bash',
  m: 'objc',
  markdown: 'markdown',
  md: 'markdown',
  mdown: 'markdown',
  mjs: 'javascript',
  mkd: 'markdown',
  ml: 'ocaml',
  mli: 'ocaml',
  mm: 'objc',
  mts: 'typescript',
  mtsx: 'typescriptreact',
  php: 'php',
  phtml: 'php',
  py: 'python',
  pyi: 'python',
  pyw: 'python',
  rake: 'ruby',
  rb: 'ruby',
  res: 'rescript',
  resi: 'rescript',
  rs: 'rust',
  sc: 'scala',
  scala: 'scala',
  sh: 'bash',
  swift: 'swift',
  tla: 'tlaplus',
  toml: 'toml',
  ts: 'typescript',
  tsx: 'typescriptreact',
  zig: 'zig',
  zon: 'zig',
  zsh: 'bash',
}

const TUI_CODE_FILETYPE_ALIASES: Record<string, string> = {
  'c#': 'csharp',
  'c++': 'cpp',
  bash: 'bash',
  c: 'c',
  cpp: 'cpp',
  csharp: 'csharp',
  css: 'css',
  dart: 'dart',
  elisp: 'elisp',
  elixir: 'elixir',
  emacs_lisp: 'elisp',
  'emacs-lisp': 'elisp',
  embedded_template: 'embedded_template',
  embeddedtemplate: 'embedded_template',
  go: 'go',
  golang: 'go',
  html: 'html',
  java: 'java',
  javascript: 'javascript',
  javascriptreact: 'javascriptreact',
  js: 'javascript',
  jsx: 'javascriptreact',
  json: 'json',
  markdown: 'markdown',
  md: 'markdown',
  objc: 'objc',
  objective_c: 'objc',
  objectivec: 'objc',
  'objective-c': 'objc',
  ocaml: 'ocaml',
  php: 'php',
  py: 'python',
  python: 'python',
  rescript: 'rescript',
  ruby: 'ruby',
  rust: 'rust',
  scala: 'scala',
  sh: 'bash',
  shell: 'bash',
  shellscript: 'bash',
  swift: 'swift',
  tla: 'tlaplus',
  'tla+': 'tlaplus',
  tlaplus: 'tlaplus',
  toml: 'toml',
  ts: 'typescript',
  tsx: 'typescriptreact',
  typescript: 'typescript',
  typescriptreact: 'typescriptreact',
  zig: 'zig',
  zsh: 'bash',
}

export function normalizeTuiCodeFiletype(language: string): string | undefined {
  const lower = language.trim().replace(/^\./, '').toLowerCase()
  if (!lower) return undefined
  return TUI_CODE_FILETYPE_ALIASES[lower] ?? TUI_CODE_FILETYPE_BY_EXTENSION[lower] ?? undefined
}

export function detectTuiCodeFiletypeFromPath(filePath?: string): string | undefined {
  if (!filePath) return undefined
  const slash = Math.max(filePath.lastIndexOf('/'), filePath.lastIndexOf('\\'))
  const name = filePath.slice(slash + 1).toLowerCase()
  const dot = name.lastIndexOf('.')
  if (dot === -1) return normalizeTuiCodeFiletype(name)
  return normalizeTuiCodeFiletype(name.slice(dot + 1))
}
