// Type surface the rest of the app consumes for the Codex app-server.
//
// The protocol types are generated by `codex app-server generate-ts` into
// `lib/codex-schema/` (see `npm run regen-codex-schema`). This file keeps
// our `Codex*` names as aliases for the official schema names, plus the
// JSON-RPC envelope helpers that aren't part of the schema.
//
// When a schema-defined shape diverges from what we actually use on the
// wire (typically when our consumer is laxer for forward-compat), we
// declare a small loosening here rather than editing the generated files.

import type {
  AppsListResponse,
  ExperimentalFeature,
  ExperimentalFeatureListResponse,
  ListMcpServerStatusResponse,
  Model,
  ModelListResponse,
  ReviewStartResponse,
  SkillsListResponse,
  Thread,
  ThreadCompactStartResponse,
  ThreadForkResponse,
  ThreadGoalClearResponse,
  ThreadGoalSetResponse,
  ThreadListResponse,
  ThreadReadResponse,
  ThreadResumeResponse,
  ThreadRollbackResponse,
  ThreadSetNameResponse,
  ThreadSettingsUpdateResponse,
  ThreadShellCommandResponse,
  ThreadStartResponse,
  ThreadTokenUsage,
  ThreadTurnsListResponse,
  TurnInterruptResponse,
  TurnStartResponse,
  TurnSteerResponse,
} from './codex-schema/v2'

import type {
  FileUpdateChange,
  McpServerStatus,
  PatchApplyStatus,
  ThreadItem,
  ThreadStatus,
  Turn,
  UserInput,
} from './codex-schema/v2'

// ServerNotification lives at the schema root (not under v2/) because it
// imports notifications from both layers.
import type { ClientRequest, InitializeResponse, ServerNotification, ServerRequest } from './codex-schema'

// JSON-RPC envelope is shared infrastructure, not part of the protocol schema.
export type CodexClientMethod = ClientRequest['method']
export type CodexRequestParams<M extends CodexClientMethod> = Extract<ClientRequest, { method: M }>['params']
export type CodexRequestArgs<M extends CodexClientMethod> =
  [CodexRequestParams<M>] extends [undefined]
    ? [params?: undefined, skipInitialize?: boolean]
    : [params: CodexRequestParams<M>, skipInitialize?: boolean]

export type CodexResponseFor<M extends CodexClientMethod> =
  M extends 'initialize' ? InitializeResponse
  : M extends 'mcpServerStatus/list' ? ListMcpServerStatusResponse
  : M extends 'experimentalFeature/list' ? ExperimentalFeatureListResponse
  : M extends 'skills/list' ? SkillsListResponse
  : M extends 'app/list' ? AppsListResponse
  : M extends 'thread/list' ? ThreadListResponse
  : M extends 'thread/read' ? ThreadReadResponse
  : M extends 'thread/turns/list' ? ThreadTurnsListResponse
  : M extends 'thread/resume' ? ThreadResumeResponse
  : M extends 'thread/start' ? ThreadStartResponse
  : M extends 'thread/fork' ? ThreadForkResponse
  : M extends 'thread/rollback' ? ThreadRollbackResponse
  : M extends 'thread/name/set' ? ThreadSetNameResponse
  : M extends 'thread/settings/update' ? ThreadSettingsUpdateResponse
  : M extends 'thread/shellCommand' ? ThreadShellCommandResponse
  : M extends 'thread/compact/start' ? ThreadCompactStartResponse
  : M extends 'thread/goal/set' ? ThreadGoalSetResponse
  : M extends 'thread/goal/clear' ? ThreadGoalClearResponse
  : M extends 'turn/start' ? TurnStartResponse
  : M extends 'turn/steer' ? TurnSteerResponse
  : M extends 'turn/interrupt' ? TurnInterruptResponse
  : M extends 'review/start' ? ReviewStartResponse
  : M extends 'model/list' ? ModelListResponse
  : unknown

export type CodexJsonRpcRequest<M extends CodexClientMethod = CodexClientMethod> = {
  jsonrpc: '2.0'
  id: string
  method: M
  params?: CodexRequestParams<M>
}

export type CodexJsonRpcResponse = {
  // The app-server echoes our string ids on responses, but server→client
  // *requests* (which also carry an id) use the server's own numeric id space.
  id?: string | number
  result?: unknown
  error?: { code?: number; message?: string; data?: unknown }
  method?: string
  params?: unknown
}

// A request the app-server sends to us (e.g. an exec/patch approval). Carries
// both an id (we must echo it on the response) and a method.
export type CodexKnownServerRequest = ServerRequest
export type CodexServerRequest =
  | CodexKnownServerRequest
  | { id: string | number; method: string; params: Record<string, unknown> }

// ── Schema re-exports (kept under our Codex* names so call sites don't churn) ──

export type CodexThread = Thread
export type CodexTurn = Turn
export type CodexThreadStatus = ThreadStatus
export type CodexThreadItem = ThreadItem
export type CodexUserInput = UserInput
export type CodexFileUpdateChange = FileUpdateChange
export type CodexPatchApplyStatus = PatchApplyStatus

export type CodexThreadReadResponse = ThreadReadResponse
export type CodexThreadResumeResponse = ThreadResumeResponse
export type CodexThreadForkResponse = ThreadForkResponse
export type CodexThreadRollbackResponse = ThreadRollbackResponse
export type CodexTurnStartResponse = TurnStartResponse
export type CodexThreadTurnsListResponse = ThreadTurnsListResponse

// ThreadListResponse adds `backwardsCursor` to the historical shape we used.
// Re-export verbatim so consumers see the new field.
export type CodexThreadListResponse = ThreadListResponse

export type CodexModel = Model
export type CodexModelListResponse = ModelListResponse

export type CodexMcpServerStatus = McpServerStatus
export type CodexMcpServerListResponse = ListMcpServerStatusResponse

export type CodexExperimentalFeature = ExperimentalFeature
export type CodexExperimentalFeatureListResponse = ExperimentalFeatureListResponse

export type CodexSkillsListResponse = SkillsListResponse
export type CodexAppsListResponse = AppsListResponse

export type CodexThreadTokenUsage = ThreadTokenUsage

// ServerNotification is a strict, closed discriminated union. We need to
// pass through arbitrary methods (e.g. `mcpServer/startupStatus/updated`
// when the codex CLI rolls out a new event) without forcing a code change,
// so widen with a string-keyed fallback. Discriminating consumers still get
// full type-narrowing on the known cases.
export type CodexKnownNotification = ServerNotification
export type CodexNotification =
  | CodexKnownNotification
  | { method: string; params: Record<string, unknown> }
