// Type surface the rest of the app consumes for the Codex app-server.
//
// The protocol types are generated by `codex app-server generate-ts` into
// `lib/codex-schema/` (see `npm run regen-codex-schema`). This file keeps
// our `Codex*` names as aliases for the official schema names, plus the
// JSON-RPC envelope helpers that aren't part of the schema.
//
// When a schema-defined shape diverges from what we actually use on the
// wire (typically when our consumer is laxer for forward-compat), we
// declare a small loosening here rather than editing the generated files.

import type {
  ListMcpServerStatusResponse,
  Model,
  ModelListResponse,
  Thread,
  ThreadForkResponse,
  ThreadListResponse,
  ThreadReadResponse,
  ThreadResumeResponse,
  ThreadRollbackResponse,
  ThreadStartResponse,
  ThreadTokenUsage,
  ThreadTurnsListResponse,
} from './codex-schema/v2'

import type {
  ExperimentalFeature,
  ExperimentalFeatureListResponse,
  FileUpdateChange,
  McpServerStatus,
  PatchApplyStatus,
  ThreadItem,
  ThreadStatus,
  Turn,
  UserInput,
} from './codex-schema/v2'

// ServerNotification lives at the schema root (not under v2/) because it
// imports notifications from both layers.
import type { ServerNotification } from './codex-schema'

// JSON-RPC envelope is shared infrastructure, not part of the protocol schema.
export type CodexJsonRpcRequest = {
  jsonrpc: '2.0'
  id: string
  method: string
  params?: unknown
}

export type CodexJsonRpcResponse = {
  // The app-server echoes our string ids on responses, but server→client
  // *requests* (which also carry an id) use the server's own numeric id space.
  id?: string | number
  result?: unknown
  error?: { code?: number; message?: string; data?: unknown }
  method?: string
  params?: unknown
}

// A request the app-server sends to us (e.g. an exec/patch approval). Carries
// both an id (we must echo it on the response) and a method.
export type CodexServerRequest = {
  id: string | number
  method: string
  params: Record<string, unknown>
}

// ── Schema re-exports (kept under our Codex* names so call sites don't churn) ──

export type CodexThread = Thread
export type CodexTurn = Turn
export type CodexThreadStatus = ThreadStatus
export type CodexThreadItem = ThreadItem
export type CodexUserInput = UserInput
export type CodexFileUpdateChange = FileUpdateChange
export type CodexPatchApplyStatus = PatchApplyStatus

export type CodexThreadReadResponse = ThreadReadResponse
export type CodexThreadResumeResponse = ThreadResumeResponse
export type CodexThreadForkResponse = ThreadForkResponse
export type CodexThreadRollbackResponse = ThreadRollbackResponse
export type CodexTurnStartResponse = { turn: Turn }
export type CodexThreadTurnsListResponse = ThreadTurnsListResponse

// ThreadListResponse adds `backwardsCursor` to the historical shape we used.
// Re-export verbatim so consumers see the new field.
export type CodexThreadListResponse = ThreadListResponse

export type CodexModel = Model
export type CodexModelListResponse = ModelListResponse

export type CodexMcpServerStatus = McpServerStatus
export type CodexMcpServerListResponse = ListMcpServerStatusResponse

export type CodexExperimentalFeature = ExperimentalFeature
export type CodexExperimentalFeatureListResponse = ExperimentalFeatureListResponse

// The schema's SkillsListResponse / AppsListResponse names differ slightly
// from what we shipped; define the precise shapes we consume.
export type CodexSkillsListResponse = {
  data: Array<{ cwd: string; skills: Array<{ name?: string; description?: string }>; errors?: string[] }>
}

export type CodexAppsListResponse = {
  data: Array<{ name: string; id?: string }>
  nextCursor: string | null
}

// ThreadTokenUsage in the schema requires `total` and `last`; our consumer
// has historically tolerated either being absent (e.g. on a freshly started
// thread). Keep the optional shape so the mapper's `?? {}` fallback still
// makes sense.
export type CodexThreadTokenUsage = {
  total?: ThreadTokenUsage['total'] | null
  last?: ThreadTokenUsage['last'] | null
  modelContextWindow?: ThreadTokenUsage['modelContextWindow']
}

// ServerNotification is a strict, closed discriminated union. We need to
// pass through arbitrary methods (e.g. `mcpServer/startupStatus/updated`
// when the codex CLI rolls out a new event) without forcing a code change,
// so widen with a string-keyed fallback. Discriminating consumers still get
// full type-narrowing on the known cases.
export type CodexKnownNotification = ServerNotification
export type CodexNotification =
  | CodexKnownNotification
  | { method: string; params: Record<string, unknown> }
